### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by mtsbatalha** [userdocs/LFTP4WIN-CORE#3]
After run pget or mirror command in WSCP nothing happens:

https://i.imgur.com/gWQIi8O.jpg

**Comment by userdocs** [comment]
Without any useful information to assist all i can say is that in my testing there are no issues i am aware of and i cannot reproduce your issue.

It could be a local issue, like a firewall.

**Comment by patrickisfrench** [comment]
I know i'm waking the dead here, but I too have this same issue. I have more information about it though. Seems to only happen when using FTPS(21) rather than SFTP(22). You can also seem to start the download by ctrl+c which will close a process that starts at the beginning of pget-to-local, the .ssh/known_hosts script? if i try to close the window these processes listed will alert that they are going to stop (see https://i.imgur.com/Hl1MFFb.jpg)
Once clicking okay, the task will start, all 5 parallel segments launch and download properly, everything works as normal. However just sending a file to pget or mirror to local will show WSCP with no progress, blank, black terminal unless one action of ctrl+c is executed or, X the window and clicking okay to stop those processes.
