### ISSUE TITLE
Slow download compared to FileZilla although "set mirror:use-pget-n 5" is used

### ISSUE THREAD

**Issue by ghost** [userdocs/LFTP4WIN-CORE#4]
Hey, first of all, I really like the idea so thanks for putting in the work. 
Here's my problem:  
When I download a test file from my sftp server I get around 18 MB/s using FileZilla. If I now download the same file with LFTP4WIN I only get around 2 - 3 MB/s.  
I simply followed the installation instructions and have the following options in the lftp.conf:
```
set mirror:parallel-directories yes
set mirror:parallel-transfer-count 2
set mirror:set-permissions off
set mirror:use-pget-n 5
```
```
set pget:default-n 5
set pget:min-chunk-size 50M
```
What could be the issue here?  
When using FileZilla I also made sure to use SFTP and not FTP since I read that FTP can sometimes be a littler faster on FileZilla.  
I also tried to limit the download speed to 1 byte in order to check that the lftp.conf actually gets used and it worked.

**Comment by userdocs** [comment]
Are you using the task manager performance tab to view your network adapters throughput?

**Comment by ghost** [comment]
Yeah, the task manager also shows ~24 Mb/s (3 MB/s) and the LFTP4WIN window shows 2.85 MB/s.  
The default values for pget and mirror are already set to use segmented downloading, right?  
Because if I use ``lftp-conf-override`` then the multisegmented download works (for pget). However if I reset the override and simply use the global config (which I assume should automatically be used) it downloads with a single thread.  
Did I maybe understand something wrong about the global config?  
Pretty sure Im at fault here.  
edit. the config here:
```
# debug 10 -o "~/lftp-debug.log"
set bmk:save-passwords true
set cache:enable no
set cmd:default-protocol sftp
set cmd:move-background true
set cmd:move-background-detach true
set cmd:parallel 1
set cmd:prompt "lftp \\[\\e[01;32m\\]\\h\\[\\e[00m\\]:\\[\\e[01;34m\\]\\w\\[\\e[00m\\] % "
set cmd:queue-parallel 1
set color:use-color auto
set dns:cache-enable no
set dns:order "inet inet6"
set ftp:ssl-allow true
set ftp:ssl-auth TLS
set ftp:ssl-force true
set ftp:ssl-protect-data true
set ftp:ssl-protect-list true
set ftps:initial-prot P
set log:enabled no
set log:enabled/xfer no
set log:level/debug 10
set log:max-size 5M
set mirror:parallel-directories yes
set mirror:parallel-transfer-count 2
set mirror:set-permissions off
set mirror:use-pget-n 9
set net:reconnect-interval-base 10
set net:timeout 10
set pget:default-n 9
set pget:min-chunk-size 50M
set sftp:auto-confirm yes
set sftp:connect-program "ssh -a -x"
set ssl:verify-certificate false
set xfer:temp-file-name *.lftp
set xfer:use-temp-file yes
```

**Comment by userdocs** [comment]
The override is there to easily change specific but relevant settings quickly. There are limitations of the WinSCP gui that cannot load existing values so it always loads as 0 but the file is only changed if you select an action. Which is why there is an option to load it after editing.

It is controlled but this function https://github.com/userdocs/LFTP4WIN-CORE/blob/master/system/scripts/functions.sh#L37#L51

If the values are set to 0 or reset to 0 it will use the lftp.conf file settings. Using the lftp.conf would be how a linux user typically controls the settings. If you have any settings in this file that are not 0, these settings will be used for relevant transfers.

With lftp, small changes are best. Start with the defaults and make small and incremental changes to optimise your transfer based on your limitations. The defaults are here https://github.com/userdocs/LFTP4WIN-CORE/blob/master/system/etc/lftp.conf

You may want to also check you don't have a bandwith shaping application like https://www.dell.com/community/Networking-Internet-Bluetooth/Beware-of-SmartByte/td-p/6130892

**Comment by ghost** [comment]
Ok, thank your for your replies. I will try to get the global config running. But as for now, my setup works. Thank you again for writing this piece of software!
