### ISSUE TITLE
Uploading FIles

### ISSUE THREAD

**Issue by ElementalCrisis** [userdocs/LFTP4WIN-CORE#8]
Hello,

Would it be possible to use LFTP4WIN for uploading files as well? Took a quick look around but didn't see an option.

**Comment by userdocs** [comment]
Not with the existing commands due to the way the it selects local / remote dirs.

It might be possible with a modified version but as far as I understand uploading uses `put` not `pget` and put only does parallel, like a normal ftp client.

https://lftp.yar.ru/lftp-man.html

```
       put [-E] [-a] [-c] [-e] [-P N] [-O base] lfile [-o rfile]

       Upload lfile with remote name rfile. If -o omitted, the base name of lfile is used as  remote
       name. Does not expand wildcards, use mput for that.

              -o <rfile>   specifies remote file name (default - basename of lfile)
              -c           continue, reput. It requires permission to overwrite remote files
              -E           delete source files after successful transfer (dangerous)
              -e           delete target file before the transfer
              -a           use ascii mode (binary is the default)
              -P N         upload N files in parallel
              -O <base>    specifies base directory or URL where files should be placed
```

So i don't think this serves any real benefit. You'd need to download using lftp on the remote using mirror/pget to achieve the same result

So if you are just uploading with no need to pget split pieces there are better options.

**Comment by ElementalCrisis** [comment]
I see, thanks for the information!

I'll go ahead and close this issue.
